# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubApi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubApi

pod 'SDWebImage', '~> 4.0'
pod 'SVProgressHUD'
pod 'Alamofire', '~> 4.6’
  target 'GitHubApiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubApiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
